name = "FSDConversion"
uuid = "a36f89f7-c8eb-4129-9265-8208fca7027b"
authors = ["BrianGuenter <1brianguenter@gmail.com>"]
version = "0.1.0"

[deps]
FastSymbolicDifferentiation = "eb9bf01b-bf85-4b60-bf87-ee5de06c00be"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
